services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MAVEN_SKIP_TEST=true
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/mydatabase
      SPRING_PROFILES_ACTIVE: hom

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: my-secret-pw
      MONGO_INITDB_DATABASE: mydatabase
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express:latest
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: my-secret-pw
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - "8081:8081"
    depends_on:
      - mongodb